sudo: required

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - docker-ce

script: mvn clean test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export APPLEPRICESBOT=proshik/applepricesbot
  - export COMMIT=${TRAVIS_COMMIT::7}
  
  - docker build -t $APPLEPRICESBOT:$COMMIT .
  - docker tag $APPLEPRICESBOT:$COMMIT $APPLEPRICESBOT:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $APPLEPRICESBOT:$TAG
