spring:
  application:
    name: applepricesbot
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: postgres
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/apple_prices_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    serialization.write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: ${APPLEPRICESBOT_LIQUIBASE_ENABLE:true}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.threadPool.threadCount: 2
      org.quartz.jobStore.isClustered: false
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
server:
  port: ${PORT:8080}

info:
  app:
    name: ${spring.application.name}
    version: ${parent.version}

telegram:
  webhook:
    enabled: ${APPLEPRICESBOT_WEBHOOK_IS_ENABLE:false}
    url: ${APPLEPRICESBOT_WEBHOOK_URL:null}
  username: ${APPLEPRICESBOT_TELEGRAMUSERNAME}
  token: ${APPLEPRICESBOT_TELEGRAMTOKEN}



