spring:
  application:
    name: applepricesbot
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  #    hibernate:
  #      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: postgres
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/applepricesbot}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      connection-timeout: 30000
      connection-test-query: SELECT 1
  profiles:
    active: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization.write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: ${APPLEPRICESBOT_LIQUIBASE_ENABLE:false}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.threadPool.threadCount: 2
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
server:
  port: ${PORT:8080}
#  tomcat:
#    max-connections: 50
#    max-threads: 1

info:
  app:
    name: ${spring.application.name}
    version: ${parent.version}

# Telegram
telegram.username: ${APPLEPRICESBOT_TELEGRAMUSERNAME}
telegram.token: ${APPLEPRICESBOT_TELEGRAMTOKEN}

# DBPATH
db.path: ${APPLEPRICESBOT_DBPATH:database.db}

#logging:
#  level:
#    org.springframework: debug

