name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    name: Java config
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
          architecture: x64
      - name: Build with Maven
        run: mvn package --file pom.xml